service: log-forwarder

frameworkVersion: '3'

provider:
  name: aws
  region: eu-west-1
  runtime: python3.9

  environment:
    S3_CONTROLPLANE_BUCKET_NAME: alpha-dev-private-eks-logs
    S3_DATAPLANE_BUCKET_NAME: alpha-dev-public-eks-logs
    LOGLEVEL: DEBUG

functions:
  forwarder:
    handler: forwarder.handler


